export const PRODUCT_ACTION_UPDATE = "PRODUCT_ACTION_UPDATE";
export const PRODUCT_DATA_FAILURE = "PRODUCT_DATA_FAILURE";
export const PRODUCT_DATA_REQUEST = "PRODUCT_DATA_REQUEST";
export const PRODUCT_DATA_SUCCESS = "PRODUCT_DATA_SUCCESS";
export const PRODUCT_DEL_FILTER = "PRODUCT_DEL_FILTER";
export const PRODUCT_SET_FILTER = "PRODUCT_SET_FILTER";
