export const PRODUCT_DATA_FAILURE = "PRODUCT_DATA_FAILURE";
export const PRODUCT_DATA_REQUEST = "PRODUCT_DATA_REQUEST";
export const PRODUCT_DATA_SUCCESS = "PRODUCT_DATA_SUCCESS";
export const PRODUCT_ACTION_UPDATE = "PRODUCT_ACTION_UPDATE";
